### ISSUE TITLE
Support for workspace (multiple projects)

### ISSUE THREAD

**Issue by WtfJoke** [remotemobprogramming/mob-vscode-gui#2]
Hi there

Is it possible to add support for [workspace](https://code.visualstudio.com/docs/editor/workspaces). 
I tried to use the plugin, but when I pressed at "Mob Start" I got the error:
`1 workspace folder required. Found 10`

**Comment by alessandrosangalli** [comment]
Hi, 

Is not possible suport multiple workspaces/folders because mob.sh need to know what is the root folder to do git actions.

**Comment by WtfJoke** [comment]
Hey @alessandrosangalli 
My idea was that it works similar like open a new terminal in a workspace.
It opens a popup which the user needs to choose the right folder/project:
![grafik](https://user-images.githubusercontent.com/7139697/202504698-29314c46-e334-47f4-99ff-a8362ebcd4c3.png)

So I press mob start... it detects if its a workspace, if so, it lets you decide on which project the mob commands should be executed.

**Comment by alessandrosangalli** [comment]
> Hey @alessandrosangalli 
> My idea was that it works similar like open a new terminal in a workspace.
> It opens a popup which the user needs to choose the right folder/project:
> ![grafik](https://user-images.githubusercontent.com/7139697/202504698-29314c46-e334-47f4-99ff-a8362ebcd4c3.png)
> 
> So I press mob start... it detects if its a workspace, if so, it lets you decide on which project the mob commands should be executed.
> 

Nice idea, i'll look in this weekend

**Comment by alessandrosangalli** [comment]
Done in V2.0.0

**Comment by WtfJoke** [comment]
Works as expected thank you @alessandrosangalli :)
