### ISSUE TITLE
mob fails when installed via homebrew on mac

### ISSUE THREAD

**Issue by steffakasid** [remotemobprogramming/mob-vscode-gui#6]
`Command failed: mob start --include-uncommitted-changes
/bin/sh: mob: command not found`

mob is installed @ `/opt/homebrew/bin/mob` if I run `/bin/sh mob` I also get `/opt/homebrew/bin/mob: /opt/homebrew/bin/mob: cannot execute binary file`. When I do `/bin/sh -c mob` everything works fine.

**Comment by alessandrosangalli** [comment]
Hi, i will add homebrew exec support tomorrow, thanks.

**Comment by alessandrosangalli** [comment]
Hi @steffakasid, i add this setting, test with your homebrew path or /bin/sh -c mob and let me know if works for you

![image](https://github.com/remotemobprogramming/vscode-mob/assets/16669471/a71931fa-2fcf-452d-94d2-560e8e0e7881)

**Comment by steffakasid** [comment]
Generally it seems to work. I could overwrite the default. But I needed to reload VSCode.
